apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
    name: acmeair-auth
    annotations:
      argocd.argoproj.io/sync-wave: "5"
spec:
  license:
    accept: true
  applicationImage: docker-na-public.artifactory.swg-devops.com/hyc-wassvt-team-image-registry-docker-local/acmeair/acmeair-auth-service:ol-jdk8-java17
  createKnativeService: false
  pullPolicy: Always
  expose: true
  route:
    path: "/auth"
  env:
  - name: USERNAME
    value: admin
  - name: PASSWORD
    value: password
  - name: ACMEAIR_STACKAA_CUSTOMER_URL
    valueFrom:
      configMapKeyRef:
        name: aa-routes
        key: customer-route
  - name: JAEGER_AGENT_HOST
    value: jaeger-all-in-one-inmemory-agent
  - name: JAEGER_AGENT_PORT
    value: '6832'
  - name: JAEGER_ENDPOINT
    value: 'http://jaeger-all-in-one-inmemory-collector:14268/api/traces'
  - name: ACCESS_LOGGING_ENABLED
    value: 'false'
  - name: TRACE_SPEC
    value: '*=info'
  - name: LOGGING_FORMAT
    value: 'simple'
  - name: DEFAULT_HTTP_PORT
    value: '9080'
  - name: DEFAULT_HTTPS_PORT
    value: '9443'
#  readinessProbe:
#    httpGet:
#      path: /health
#      port: 9080
#    initialDelaySeconds: 10
#    periodSeconds: 5
#  livenessProbe:
#    httpGet:
#      path: /health
#      port: 9080
#    initialDelaySeconds: 120
#    periodSeconds: 15
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 9080 
